apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service
  labels:
    app: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
    spec:
      containers:
      - name: borrow-service
        image: borrow-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 240
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/borrowdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: "org.apache.kafka.common.serialization.StringSerializer"
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: "org.apache.kafka.common.serialization.StringSerializer"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: "borrow-service-group"
        - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
          value: "earliest"
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: "org.apache.kafka.common.serialization.StringDeserializer"
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: "org.apache.kafka.common.serialization.StringDeserializer" 