apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-external
      protocol: TCP
      port: 29092
      targetPort: 29092
    - name: kafka-controller  # Added controller port
      protocol: TCP
      port: 29093
      targetPort: 29093
  type: ClusterIP